"""Versioned contracts shared by SATQUERY specialists, API, and frontend."""

from .models import (
    AnalysisRequest,
    AssetFormat,
    AssetStatus,
    ContractModel,
    EvidenceArtifact,
    EvidenceKind,
    ExecutionTrace,
    ImageAsset,
    ImageRole,
    PlanStep,
    PlanStepStatus,
    RasterMetadata,
    RequestedCapability,
    SensorType,
    Specialist,
    SpecialistResult,
    SpecialistStatus,
    TaskPlan,
    TaskType,
    TraceEvent,
    TraceOutcome,
)

CONTRACT_VERSION = "0.2"

__all__ = [
    "AnalysisRequest",
    "AssetFormat",
    "AssetStatus",
    "CONTRACT_VERSION",
    "ContractModel",
    "EvidenceArtifact",
    "EvidenceKind",
    "ExecutionTrace",
    "ImageAsset",
    "ImageRole",
    "PlanStep",
    "PlanStepStatus",
    "RasterMetadata",
    "RequestedCapability",
    "SensorType",
    "Specialist",
    "SpecialistResult",
    "SpecialistStatus",
    "TaskPlan",
    "TaskType",
    "TraceEvent",
    "TraceOutcome",
]
