import { Crosshair, Image as ImageIcon, Layers, RotateCcw, ZoomIn, ZoomOut } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import maplibregl from "maplibre-gl";
import "maplibre-gl/dist/maplibre-gl.css";
import type { AnalysisMode, UploadedAsset } from "../contracts";
export function Viewer({ mode, assets }: { mode: AnalysisMode; assets: UploadedAsset[] }) {
  const mapElement = useRef<HTMLDivElement>(null); const [zoom, setZoom] = useState(1); const [layerOpen, setLayerOpen] = useState(false); const hasMapStyle = false;
  useEffect(() => { if (!hasMapStyle || !mapElement.current) return; const map = new maplibregl.Map({ container: mapElement.current, style: import.meta.env.VITE_MAP_STYLE_URL }); return () => map.remove(); }, [hasMapStyle]);
  const imageAsset = assets.find((asset) => asset.previewUrl);
  return <div className="viewer"><div className="viewer-toolbar"><div className="viewer-tabs"><button className="viewer-tab active"><ImageIcon size={15} /> Imagery</button><button className="viewer-tab"><Layers size={15} /> Layers</button></div><div className="viewer-tools"><button className="icon-button" title="Zoom out" onClick={() => setZoom(Math.max(.5, zoom - .25))}><ZoomOut size={16} /></button><span className="zoom-readout">{Math.round(zoom * 100)}%</span><button className="icon-button" title="Zoom in" onClick={() => setZoom(Math.min(2, zoom + .25))}><ZoomIn size={16} /></button><button className="icon-button" title="Reset view" onClick={() => setZoom(1)}><RotateCcw size={15} /></button><button className="icon-button" title="Toggle layers" onClick={() => setLayerOpen(!layerOpen)}><Layers size={16} /></button></div></div><div className="viewer-stage" style={{ transform: `scale(${zoom})` }}>{hasMapStyle ? <div ref={mapElement} className="maplibre-container" /> : imageAsset ? <img src={imageAsset.previewUrl} alt="Selected satellite imagery" /> : <div className="viewer-empty"><Crosshair size={28} /><strong>Viewer ready</strong><span>Load imagery to inspect a scene.</span><small>MapLibre activates when a map style and georeferenced source are available.</small></div>}</div>{layerOpen && <div className="layer-popover"><strong>Visible layers</strong><label><input type="checkbox" defaultChecked /> {mode === "change" ? "Change mask (pending)" : mode === "optical-sar" ? "Fused evidence (pending)" : "Imagery"}</label><label>Opacity <input type="range" defaultValue="100" /></label></div>}<div className="viewer-footer"><span><Crosshair size={13} /> Coordinates unavailable</span><span>EPSG: not detected</span></div></div>;
}
